#!/usr/bin/env bash

echo "<!-- autogenerated by $0 -->" > README.md

last_theme=""
find . -regex '.*\(jpg\|jpeg\|png\)' | sort | while read -r img; do
    theme=$(echo $img | awk -F '_' '{print $1}' | tr -d './')

    if [[ "$theme" != "$last_theme" ]]; then
        echo "## $theme" >> README.md
        last_theme=$theme
    fi

    echo -e "![$img]($img)\n" >> README.md
done
